### PR TITLE
LPS-144367 Optimize the query to use indexer

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi, this is the PR for the https://issues.liferay.com/browse/LPP-43340 and https://issues.liferay.com/browse/LPS-144367.
Currently, there's no member on our side available for the internal review so I made this PR directly. Sorry for this inconvenience.
Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
https://github.com/liferay-usm/liferay-portal/pull/392

**Comment by holatuwol** [comment]
While the changes make sense with some source formatting, I re-read the description for LPS-144367 and noticed that the query that the customer was complaining about contains `userId` as one of the fields. The query we're updating here searches the `classPK` column, not the `userId` column.

Can you explain how this fixes the query mentioned in LPS-144367?

**Comment by holatuwol** [comment]
I've read through LPP-43340 and updated the description for LPS-144367 to reflect the actual bug.

**Comment by hongvo2308** [comment]
Hi @holatuwol 
Yes, I have asked them to use the fixpatch for https://issues.liferay.com/browse/LPS-137164.
Thank you.

**Pull request closed without merging**
