### PR TITLE
[TS] LPP-45582> LPS-156074 The target attribute for the Link in the CKEditor in Knowledge Base portlet is removed after saving

### PR DESCRIPTION
**Pull request by chileces**
Hello Team,
this is a PR for ticket https://issues.liferay.com/browse/LPP-45582, please help to review and give us feedback
best regards,
cc: @thienquach87
Chi le

### CODE REVIEW

**Comment by chileces** [comment]
ci:test:bundle

**Comment by holatuwol** [comment]
According to the xsd, we should be able to do a `regexp-list` followed by a `literal-list`.

https://github.com/andresriancho/owaspantisamy/blob/master/dotNet/current/source/owaspantisamy/resources/antisamy.xsd#L62-L65

Since the latter two are literals, can you split it up into two lists and see if the issue is still fixed?

**Comment by thienquach87** [comment]
@holatuwol 
Thank you for your suggestion. I separated it following your idea

**Comment by holatuwol** [comment]
https://github.com/liferay-appsec/liferay-portal/pull/698

**Pull request closed without merging**
