### PR TITLE
LPS-143582 Displaying organization with organization site

### PR DESCRIPTION
**Pull request by huynguyen-codeengine**
https://issues.liferay.com/browse/LPP-43378
https://issues.liferay.com/browse/LPS-143582

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Sent to https://github.com/hongvo2308/liferay-portal/pull/13 with additional commits.  Waiting on @hongvo2308 to test new changes.

**Comment by hongvo2308** [comment]
Hi @ChrisKian 
I have tested the https://github.com/hongvo2308/liferay-portal/pull/13 and it works as my expectation. Thank you.
I would like to clarify what I should do next on this one? Shall I open a new PR with your commits or you will proceed next steps?
Thank you.

**Comment by ChrisKian** [comment]
Hi @hongvo2308,
I've opened a PR on my own repo to run ci.  If everything looks good, I'll forward you PR to the appropriate engineering team.

https://github.com/ChrisKian/liferay-portal/pull/309

**Comment by ChrisKian** [comment]
PR passed all SF and Relevant tests.  Sent to https://github.com/liferay-echo/liferay-portal/pull/6711

**Comment by hongvo2308** [comment]
Hi @ChrisKian 
Thank you for the information.

**Pull request closed without merging**
