### PR TITLE
LPS-149558, LPS-149559 Validation for importing language key

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi,
This one is the PR for the tickets:
https://issues.liferay.com/browse/LPS-149558
https://issues.liferay.com/browse/LPS-149559
The original PR at https://github.com/hongvo2308/liferay-portal/pull/18 has passed my review.
Please review this PR and leave your comments.
Thank you.

CC: @tototrinh

### CODE REVIEW

**Comment by Sharryxue** [comment]
Hello @tototrinh @hongvo2308 
Thanks for sending and reviewing the commits. I'd rebase and resend the commits to usm repo to run the relevant tests and for devs to review. 
View [liferay-usm/liferay-portal#506](https://github.com/liferay-usm/liferay-portal/pull/506).

**Comment by tototrinh** [comment]
@Sharryxue, I added a commit [784ab4b](https://github.com/liferay-ts-reviewer/liferay-portal/pull/32/commits/784ab4b3909462cd11126d2bfdcf47e26faf3e86) to resolve the SematicVersion issue. Thanks.

**Comment by Sharryxue** [comment]
Thanks so much for sending the additional fix @tototrinh , I'd force updated the commits in [liferay-usm/liferay-portal#506](https://github.com/liferay-usm/liferay-portal/pull/506).

**Comment by tototrinh** [comment]
Hi @Sharryxue, I update the last commit [c9ed26d](https://github.com/liferay-ts-reviewer/liferay-portal/pull/32/commits/c9ed26de6736bb042517089226ab50954daef2ea) to resolve the conflict. Thanks

**Comment by Sharryxue** [comment]
Thanks for sending the fix @tototrinh, just updated the original pr [liferay-usm/liferay-portal#506](https://github.com/liferay-usm/liferay-portal/pull/506).

**Comment by tototrinh** [comment]
Hi @Sharryxue, I updated the code base based on comments from the reviewer. Thanks.

**Comment by tototrinh** [comment]
Hi @Sharryxue, could you please take the time to update the PR with these commits? Thanks in advance.

**Comment by Sharryxue** [comment]
Resend, view [liferay-usm/liferay-portal#554](https://github.com/liferay-usm/liferay-portal/pull/554)

**Comment by tototrinh** [comment]
Hi @Sharryxue, I updated the code based on Brian Chan and Drew Brokke comments. Please help to forward this again. Thanks so much.

**Comment by tototrinh** [comment]
This change was merged. Thanks @Sharryxue @hongvo2308  for your help
@hongvo2308 please help closed it. Thanks.

**Pull request closed without merging**
