### PR TITLE
LPS-153858 Redirect Interval for 404 not allowing floats to set 30 minutes

### PR DESCRIPTION
**Pull request by sontruongces**
Hi team,
This PR is for fixing [LPS-153858](https://issues.liferay.com/browse/LPS-153858) and the original PR at sontruongces#17 has passed my review. Please help me to review and give me feedback.
Thanks!
cc: @TaiPhamLR

### CODE REVIEW

**Comment by TaiPhamLR** [comment]
ci:test

**Comment by TaiPhamLR** [comment]
ci:test:bundle

**Comment by TaiPhamLR** [comment]
ci:test:bundle

**Comment by holatuwol** [comment]
https://github.com/liferay-lima/liferay-portal/pull/3303

**Pull request closed without merging**
