### PR TITLE
LPS-144008 Escape title in StyleBook to avoid XSS

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi,
This is the PR for the issue https://issues.liferay.com/browse/LPP-43444 and https://issues.liferay.com/browse/LPS-144008. Currently, there's no one available for the internal review on our side so I made this PR directly. Sorry for this inconvenience.
Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
If we proceed with this change, I think it would make sense to apply the same changes to all classes which extend BaseClayCardTag.

For now, I'm currently checking with the product team to see if they left the unescaped version for backwards compatibility reasons and plan to open a PTR if I do not get a response by early next week.

https://liferay.slack.com/archives/CNBG06JS3/p1640325757462300

**Comment by holatuwol** [comment]
The product team has replied indicating that updating the tag library makes sense. Can you update all the classes which extend BaseClayCardTag?

**Comment by hongvo2308** [comment]
Hi @holatuwol 
Yes, I will update that.
Thank you.

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I found there's the subtitle https://github.com/liferay-ts-reviewer/liferay-portal/blob/92e7d2849f5bea0de5ea0caa2f78c1bd699ff342/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/soy/VerticalCardTag.java#L102 .Do you think it could be a threat ? And where it is used ?

**Comment by holatuwol** [comment]
Checking files for the use of `subtitle=`, it looks like it's used in frontend-taglib-clay-sample-web.

```bash
for file in $(git ls-files -- '*.jsp' | xargs grep -l '<clay:[^>]*-card$'); do
  matches=$(
  cat ${file} | tr -d '\n' | sed 's/[[:space:]][[:space:]]*/ /g' | grep -oP '<clay:[^>]*-card[^-].*?/>' | grep -F 'subtitle='
  cat ${file} | tr -d '\n' | sed 's/[[:space:]][[:space:]]*/ /g' | grep -oP '<clay:[^>]*-card[^-].*?</clay:[^>]*-card>' | grep -F 'subtitle='
  )
  if [ "" != "${matches}" ]; then
    echo ${file}
  fi
done
```

However, I added an XSS string and found that subtitle isn't affected by this, which indicates that it's actually an issue in the way title is handled differently from subtitle. Checking the source for Clay, the issue is that when it invokes ClayLink, it doesn't escape the incoming string, which means this only affects title:

https://github.com/liferay/clay/blob/2.x/packages/clay-card/src/ClayCardBase.soy#L143-L147

I'll forward your solution as-is to the frontend SME and see if they feel that this is the right approach, or if we should do something to ClayCardBase.soy instead.

**Comment by holatuwol** [comment]
https://github.com/antonio-ortega/liferay-portal-ee/pull/133

**Pull request closed without merging**
