### PR TITLE
LPS-145375 Remove the OpenSSOFilter in the liferay-web.xml

### PR DESCRIPTION
**Pull request by tototrinh**
Please help review this PR and leave your comments. Thanks.
The issue is https://issues.liferay.com/browse/LPP-43770 and https://issues.liferay.com/browse/LPS-145375
cc: @hongvo2308
**Step to reproduce:** 
1. Navigate to _webapps/ROOT/WEB-INF/shielded-container-lib/_ and open up the portal-impl.jar
2. Inside _portal-impl.jar_, navigate to the _META-INF_ folder.
3. Copy the _portal-log4j.xml_ file to _webapps/ROOT/WEB-INF/classes/META-INF_.
4. Navigate to _webapps/ROOT/WEB-INF/classes/META-INF_, and rename the copied _portal-log4j.xml_ file to _portal-log4j-ext.xml_.
5. Open up the file and modify the following:
From
`<Logger level="FATAL" name="com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterHelper" />`
To
`<Logger level="ERROR" name="com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterHelper" />`
6. Save changes to _portal-log4j-ext.xml_
7. Start server and see catalina log

### CODE REVIEW

**Comment by holatuwol** [comment]
@tototrinh Do you know why there's no error for JSONContentTypeFilter? According to a search, that one should have errors as well.

```bash
for file in $(grep 'filter-class' portal-web/docroot/WEB-INF/liferay-web.xml  | cut -d '>' -f 2 | cut -d '<' -f 1 | tr '.' '/' | awk '{ print "portal-impl/src/" $1 ".java" }'); do
  test -f ${file} || echo ${file};
done
```

**Comment by hongvo2308** [comment]
Hi @holatuwol 
Yes, It also has an error on the JSONContentTypeFilter. But I am not sure if I should include it in this PR not.
So we need to include it in this PR too, is it correct ?
Thank you.

**Comment by holatuwol** [comment]
@hongvo2308 Yes, please include the change in this PR as well.

**Comment by hongvo2308** [comment]
Hi @holatuwol @tototrinh 
I have updated this PR. Please review it again and leave your comments.
Thank you.

**Comment by holatuwol** [comment]
https://github.com/liferay-core-infra/liferay-portal/pull/256

**Pull request closed without merging**
