### PR TITLE
LPS-143292 - Update Guest permission for creating document by Drag and Drop

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi,
This PR has passed my review.
LPP Ticket: https://issues.liferay.com/browse/LPP-43300
LPS Ticket: https://issues.liferay.com/browse/LPS-143292
Please take a look at it and leave your comments.
Thank you.

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Hi @hongvo2308 and @HuongNguyen-gs,

Could you clarify for me whether this is supposed to be reproducible in Master or not? From the ticket it looks like this isn't, but this solution is being applied to Master. Could you maybe give an explanation for what's going on? Thanks!

**Comment by hongvo2308** [comment]
Hi @wanderlast 
This issue is not reproducible in the master. But we found the BE code are the same between master and 7.1.x so we decide to apply this to the master to keep the consistency. I am not sure if this is a correct approach.
So for this case, we should only apply for 7.1.x, is it correct ?
Thank you.

**Comment by wanderlast** [comment]
Hi @hongvo2308,

It's typically ok to apply to master to keep consistency, but then we need to question what fixed it in Master that:

1. isn't in 7.1 
2. can't be brought back to 7.1 

Since that's typically the first thing the ER team will ask us about. Do we know why it's fixed in Master and what fixed it?

**Comment by hongvo2308** [comment]
Since now @sontruongces is taking responsibility for this ticket. Please provide the information for the question above.
Thank you.

**Comment by sontruongces** [comment]
> 

@holatuwol Hong said all the thing that I know about it so please help me clarify these question.

**Comment by holatuwol** [comment]
The issue happens in 7.1.x due to the unique fix added to resolve [LPS-97133](https://issues.liferay.com/browse/LPS-97133), which creates a private "control panel" layout within the site in order to serve as the page that you edit when you updating a content page.

* https://github.com/liferay/liferay-portal-ee/commit/c4964b1c066dd8c91a743bc0a2ebc97a85f487f8
* https://github.com/liferay/liferay-portal-ee/blob/fix-pack-dxp-17-7110/modules/apps/layout/layout-api/src/main/java/com/liferay/layout/util/GroupControlPanelLayoutUtil.java

These pages never existed in the implementation in master, and they are automatically deleted after upgrading from 7.1.x to any subsequent release via an upgrade process added in [LPS-108805](https://issues.liferay.com/browse/LPS-108805).

* https://github.com/liferay/liferay-portal/commit/c8fe2327f967e88747c1556648e5a8227d7d901d
* https://github.com/liferay/liferay-portal/blob/7.4.1-ga2/modules/apps/fragment/fragment-service/src/main/java/com/liferay/fragment/internal/upgrade/v1_1_0/PortletPreferencesUpgradeProcess.java

As these changes do not exist in master, there isn't an inconsistency between whether the current code in `EditFileEntryImageEditorMVCActionCommand` and `EditFileEntryMVCActionCommand` sees private pages and whether the tag library code in `InputPermissionsParamsTag` sees private pages, and so the issue isn't reproducible in master.

**Comment by wanderlast** [comment]
Thanks Minhchau for the write-up! From the sounds of it, this should be a fix sent to 7.1 only then with this explanation attached.

**Comment by holatuwol** [comment]
I've sent the unique 7.1.x to the SME.

https://github.com/dacousalr/liferay-portal-ee/pull/261

I'll leave this open in case the SME asks for us to route it through master.

**Comment by holatuwol** [comment]
SME has accepted the idea that this should be a unique fix on branch, so I'll close out this pull request.

**Pull request closed without merging**
