### PR TITLE
LPS-160598 Add delete comment after delete answer

### PR DESCRIPTION
**Pull request by thienquach87**
Dear Team,
   
   This is the PR for fixing this ticket: https://issues.liferay.com/browse/LPS-160598. Please help review and leave your comments.
cc: @sontruongces.

Regards,
Thien

### CODE REVIEW

**Comment by holatuwol** [comment]
Why is this deleted using frontend logic instead of backend logic?

**Comment by sontruongces** [comment]
> Why is this deleted using frontend logic instead of backend logic?

@holatuwol, I see the logic applied is in 7.3.x and is still used for now (https://github.com/liferay/liferay-portal-ee/blob/7.3.x/modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/components/Answer.es.js#L50-L64). I know it's kind of weird when using the logic in 7.3.x to apply to master. But it is the only solution that I can use to fix the issue.

**Comment by holatuwol** [comment]
Ah, if this is logic that already exists in a past version, then we can treat this as a regression bug and forward to https://github.com/liferay-frontend/liferay-portal as-is.

**Comment by thienquach87** [comment]
This PR was forwarded to https://github.com/liferay-frontend/liferay-portal/pull/2665

**Pull request closed without merging**
