### PR TITLE
LPS-141922 "assetentry.title" is not updated when restoring content

### PR DESCRIPTION
**Pull request by huynguyen-codeengine**
When restoring a Web-content from trash, it will get the latest journal-article with the latest title. But when get the asset-entry from that journal-article, it only use 2 params ResourcePrimKey and ClassName, so when the AssetEntryPersistence queries in the DB by those 2 params, the asset-entry now have the old title and when updating, the title will not change. The solution to have the latest title is when get the asset-entry from journal-article, we have to send the latest title also to set the title field of asset-entry before updating. So that I create a new updateVisible() method with a new param - title.

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by quanhuynhces** [comment]
ci:test:sf

**Comment by quanhuynhces** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
It looks like it's failing a baseline test. If it's only web content that appears to be affected by this restore from recycle bin issue, can you try implementing it without an API change?

```java
AssetEntry entry = _assetEntryLocalService.getEntry(
    JournalArticle.class.getName(), article.getResourcePrimKey());

entry.setTitle(article.getTitleMapAsXML());

_assetEntryLocalService.updateVisible(entry, true);
```

**Comment by quanhuynhces** [comment]
@holatuwol thank you, I will try again.

**Comment by quanhuynhces** [comment]
Hi @holatuwol 
I have tried to find another ways but I still can not fix this issue without changing the API. Can you check it again? And please tell me if you have any questions.

**Comment by holatuwol** [comment]
It looks like the issue is actually due to an earlier call when moving the asset entry to the recycle bin.

I've applied a variation of your changes as a second commit (the variation described in my earlier comment), and I've left it up to the reviewers to decide how to proceed with the two sets of changes.

https://github.com/liferay-echo/liferay-portal/pull/6416

**Pull request closed without merging**
