### PR TITLE
[TS] LPP-45716 -> LPS-156889 Fix layout look and feel missing css

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Hi team,
This is the PR for the Ticket: [https://issues.liferay.com/browse/LPP-45716](https://issues.liferay.com/browse/LPP-45716)
The original PR at TaiPhamLR#2 has passed my review. Please help me review this PR and leave your comments.
Thanks.
@sontruongces

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:bundle

**Comment by holatuwol** [comment]
Reviewing these changes, I don't understand how this fixes the issue.

Can you update the ticket with steps to reproduce in master?

**Comment by sontruongces** [comment]
> Reviewing these changes, I don't understand how this fixes the issue.
> 
> Can you update the ticket with steps to reproduce in master?

@holatuwol, I updated steps to reproduce in master on the ticket: https://issues.liferay.com/browse/LPS-156889.Thanks!

**Comment by holatuwol** [comment]
https://github.com/liferay-echo/liferay-portal/pull/8795

**Pull request closed without merging**
