### PR TITLE
[TS] LPP-44652 > LPS-150991 Add proxy path

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi,
This is the PR for the ticket https://issues.liferay.com/browse/LPP-44652.
The original PR at https://github.com/hongvo2308/liferay-portal/pull/22 has passed my review. Please review it and leave your comments.

Thank you

CC: @sontruongces

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:bundle

**Comment by holatuwol** [comment]
### .java matches

When I check to see if there are other instances where there is a call to `getContextPath()` without a call to `getPathProxy()` inside of `.jsp` files, I see that there are 2 files which still have the issue.


```bash
git ls-files -- '*.java' | xargs grep -Fl 'getStaticResourceURL' | xargs grep -Fl 'getContextPath()' | xargs grep -L 'getPathProxy()'
```

These are the affected files:

* https://github.com/liferay/liferay-portal/blob/7.4.1-ga2/modules/apps/change-tracking/change-tracking-web/src/main/java/com/liferay/change/tracking/web/internal/servlet/taglib/ChangeTrackingIndicatorDynamicInclude.java#L116-L134
* https://github.com/liferay/liferay-portal/blob/7.4.1-ga2/modules/apps/depot/depot-web/src/main/java/com/liferay/depot/web/internal/servlet/taglib/StagingIndicatorDynamicInclude.java#L349-L353

### .jsp matches

When I check to see if there are other instances where there is a call to `getContextPath()` without a call to `getPathProxy()` inside of `.jsp` files, I see that there are 39 files which still have the issue.

```bash
git ls-files -- '*.jsp*' | xargs grep -Fl 'getStaticResourceURL' | xargs grep -Fl 'getContextPath()' | xargs grep -L 'getPathProxy()'
```

Since there are so many, it doesn't make sense to link them here.

### Open questions

That there are so many matches leads me to the following questions:

1. Should `Portal.getStaticResourceURL` be handling this, rather than us having to hard-code the full path, including the portal proxy path and the application context path, every time?
2. There are other matches which are not calls to `getStaticResourceURL`, such as setting up the contextPath variable which is then used by React (separate from the portal itself) and iframe URLs. Are these also affected?
```
git ls-files -- '*.jsp*' | xargs grep -L 'getStaticResourceURL' | xargs grep -Fl 'getContextPath()' | xargs grep -L 'getPathProxy()'
```

**Comment by sontruongces** [comment]
> 

@holatuwol I checked question 2 and these files are also affected. For the first question I create a [PTR](https://issues.liferay.com/browse/PTR-3050). Thanks!

**Comment by sontruongces** [comment]
@holatuwol, The engineer leave a comment on the [PTR](https://issues.liferay.com/browse/PTR-3050#comment-2683484), look like it's hard to use **Portal.getStaticResourceURL** to handle this. Besides they give another solution. Could you please take a look at his comment and give me some advice that which way is the best approach to fix it? And do I need to fix all the files that you listed up there also? Thanks!

**Comment by holatuwol** [comment]
Sorry I missed your comment.

My understanding based on the comment left on the PTR by the SME is that we should:

* identify how to test all 41 instances where it appears to be wrong
* update the LPS with all X test cases, where X is how many of those 41 instances are actually wrong
* fix all of them in this pull request

**Comment by sontruongces** [comment]
@holatuwol I updated the fix and left a [comment](https://issues.liferay.com/browse/LPS-150991#comment-2696596) on the LPS-150991. Please help me review the fix. Thanks!

**Comment by holatuwol** [comment]
https://github.com/liferay-core-infra/liferay-portal/pull/964

**Pull request closed without merging**
