### PR TITLE
[TS] LPP-45272 > LPS-154652

### PR DESCRIPTION
**Pull request by tototrinh**
This PR is for the ticket https://issues.liferay.com/browse/LPP-45272. Please help me to review it and leave your comments.
Thank you.

PS: You will need to install the ImageMagick based on these instructions https://gist.github.com/hurricup/e14ae5bc47705fca6b1680e7a1fb6580 and https://issues.liferay.com/browse/LPS-151510 to test.
Update the portal-ext.properties with this value
`mime.types.web.images=image/gif,image/jpeg,image/pjpeg,image/png,image/x-png,image/heic`

cc @hongvo2308

### CODE REVIEW

**Comment by tototrinh** [comment]
ci:test:bundle

**Comment by holatuwol** [comment]
Enabling the portal property without having imagemagick installed results in the file conversion failing, but no error message appears in the UI, but a stack trace in the logs. The same thing error is seen if you have imagemagick support, but if it was not compiled with HEIC support.

At the least, we should have some kind of error in the UI showing that the image conversion failed.

**Comment by holatuwol** [comment]
Enabling the portal property without having imagemagick installed results in the file conversion failing, but no error message appears in the UI, but a stack trace in the logs. The same thing error is seen if you have imagemagick support, but if it was not compiled with HEIC support.

At the least, we should have some kind of error in the UI showing that the image conversion failed.

**Comment by hongvo2308** [comment]
Hi @holatuwol 
I have added some error displays for this one. Could you please review it again and leave your comments.
Thank you.

**Comment by hongvo2308** [comment]
ci:test:bundle

**Comment by holatuwol** [comment]
https://github.com/liferay-lima/liferay-portal/pull/3104

**Pull request closed without merging**
