### PR TITLE
LPS-141903 Only count the assignee with the active users

### PR DESCRIPTION
**Pull request by huynguyen-codeengine**

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hi @huynguyen-codeengine,
The semver failure is likely related, since the changes add a protected method to the API.  Please commit those changes and force-push when ready, thanks!

**Comment by holatuwol** [comment]
I don't see a packageinfo file in portal-impl that matches the com.liferay.portal.service.impl package, so this failure might be a fluke.

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Looks good, sent to https://github.com/liferay-usm/liferay-portal/pull/333

**Pull request closed without merging**
