### PR TITLE
Lps 141019 Restrict mentioning user in the site they could not access to

### PR DESCRIPTION
**Pull request by hongvo2308**
This PR pass my review
### Original issue
https://issues.liferay.com/browse/LPP-42805
### Issue Summary
User notification with broken link
### Reproduce Steps
https://issues.liferay.com/browse/LPS-141019
### @tototrinh solution:
She added the layout id information to the controller. Then make sure only mention the user has VIEW permission on that layout.

### CODE REVIEW

**Comment by holatuwol** [comment]
If you update [DiscussionTag.java](https://github.com/liferay/liferay-portal/blob/7.4.2-ga3/modules/apps/comment/comment-taglib/src/main/java/com/liferay/comment/taglib/servlet/taglib/DiscussionTag.java#L133-L147) and set a `p_l_id` parameter on the URL-generating methods (there are three of them: `getEditorURL`, `getFormAction`, `getPaginationURL`), you can remove the changes to the following files:

* comment-taglib/src/main/java/com/liferay/comment/taglib/internal/struts/EditDiscussionStrutsAction.java
* comment-taglib/src/main/java/com/liferay/comment/taglib/internal/struts/GetEditorStrutsAction.java
* comment-taglib/src/main/resources/META-INF/resources/discussion/js/Comments.js
* comment-taglib/src/main/resources/META-INF/resources/discussion/page.jsp

Additionally, it's possible for someone to not see a public page, and to not see a portlet on the page even if they have permission to see the page. So rather than the checks you have now, it would be better to check whether the person can see the portlet on the page using [PortletPermissionUtil.contains](https://github.com/liferay/liferay-portal/blob/7.4.2-ga3/portal-kernel/src/com/liferay/portal/kernel/service/permission/PortletPermissionUtil.java#L122-L129).

**Comment by tototrinh** [comment]
Hi @holatuwol, Thanks for your feedback. I have updated the code, please review it again. Thanks.

**Comment by holatuwol** [comment]
With your changes, it looks like this existing code is no longer necessary:

* https://github.com/liferay/liferay-portal/blob/7.4.2-ga3/modules/apps/comment/comment-taglib/src/main/java/com/liferay/comment/taglib/internal/struts/GetCommentsStrutsAction.java#L76-L80
* https://github.com/liferay/liferay-portal/blob/7.4.2-ga3/modules/apps/comment/comment-taglib/src/main/java/com/liferay/comment/taglib/internal/struts/GetEditorStrutsAction.java#L72-L76

Can you check to see if everything still works as expected if you were to remove that code?

**Comment by tototrinh** [comment]
Hi Minh Chau,
I checked in my local and found that the editor tag will not be shown when clicking the reply button if we remove the lines you mentioned
https://github.com/liferay/liferay-portal/blob/7.4.2-ga3/modules/apps/frontend-editor/frontend-editor-taglib/src/main/java/com/liferay/frontend/editor/taglib/servlet/taglib/EditorTag.java#L432-L437
image
I need to set Ppid to themeDisplay to be able to check Portlet permission, so I add the p_p_id to the URL. I think I could replace portletId with p_p_id instead of using both.

**Comment by holatuwol** [comment]
> I think I could replace portletId with p_p_id instead of using both.

No, I was just mistaken about the code flow for `WebKeys.PORTLET_ID`, we'll proceed as-is.

**Comment by holatuwol** [comment]
https://github.com/liferay-lima/liferay-portal/pull/2485

**Pull request closed without merging**
