### PR TITLE
LPS-155035 The ar-SA is not aligned on the add language key page

### PR DESCRIPTION
**Pull request by chileces**
Hello team,
this is the PR for the ticket https://issues.liferay.com/browse/LPS-155035
the original PR has passed my review https://github.com/chileces/liferay-portal/pull/9
Please review this one and leave your comments.
Thank you.
@thienquach87

### CODE REVIEW

**Comment by chileces** [comment]
ci:test:bundle

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
Translation Management falls under https://github.com/liferay-lima/liferay-portal

**Comment by holatuwol** [comment]
https://github.com/liferay-lima/liferay-portal/pull/3178

**Pull request closed without merging**
