### PR TITLE
[TS] LPP-45544 -> LPS-155924 NullPointerException in Knowledge Base Search

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Hello Team,
This is a PR for the ticket [https://issues.liferay.com/browse/LPS-155924](https://issues.liferay.com/browse/LPS-155924)
Please help to review and give us feedback.
Best regards,
Tai Pham,
@Chilesces

### CODE REVIEW

**Comment by evibudai** [comment]
Hi @TaiPhamLR,
Can you give me an update on this PR? When it will be reviewed? Are you sure that this is the right team to send to? I do not see reviewer, assignee or label on it. Usually these are automatically filled out.

Best regards,
Évi

**Comment by holatuwol** [comment]
ci:test:bundle

**Comment by holatuwol** [comment]
@evibudai For now, this is part of the internal technical support review process, where pull requests from APAC are first reviewed in the USA before they are forwarded to product teams.

**Comment by holatuwol** [comment]
https://github.com/liferay-lima/liferay-portal/pull/3199

**Comment by evibudai** [comment]
Hi @holatuwol,
Thank you for the information! :)

**Pull request closed without merging**
